const RESIZE_DELAY = 200;
const FPS = 20;
const MAX_NUM_STATES = 5;
const DEFAULT_NUM_STATES = 4;
const DEFAULT_CELL_SIZE = 5;

export {
    RESIZE_DELAY,
    FPS,
    MAX_NUM_STATES,
    DEFAULT_NUM_STATES,
    DEFAULT_CELL_SIZE
};

