const FPS = 60;
const FRAME_DURATION = 1000 / FPS;
const RESIZE_DELAY = 200;
const MAX_NUM_STATES = 5;
const DEFAULT_NUM_STATES = 4;
const DEFAULT_CELL_SIZE = 5;
const SCROLL_DIST = 2;

export {
    FRAME_DURATION,
    RESIZE_DELAY,
    MAX_NUM_STATES,
    DEFAULT_NUM_STATES,
    DEFAULT_CELL_SIZE,
    SCROLL_DIST
};

